### ISSUE TITLE
Selecting a repo issue

### ISSUE THREAD

**Issue by vany365** [calcom/synclinear.com#103]
While setting up i get to step 4. The problem is the repo i would like to select is not available. I see personal repos and repos im a member of but zero repos for teams that I am an owner/admin of. Is there a solution so i can populate the missing repos?

**Comment by tedspare** [comment]
Thanks @vany365 - sorry to hear that. It currently shows your first 100 most-recently accessed repos - is it possible those repos were accessed long ago? Otherwise, could you double-check that you have access to those repos (even if you're the admin of the team)?

**Comment by tedspare** [comment]
Hey @vany365, could you give this another try? We made some changes to the repo selector

**Comment by aspiers** [comment]
@tedspare I have the same problem because the repo I want to choose is either past the bottom of the browser viewport, or perhaps not even in the first 100 repos (I have 520 repos in my account).  Even when I zoom out to an unreadably small font it shows less than 100 repos (see below), so I'm a bit confused how this is supposed to work?  I tried to inspect the HTML so that I could edit it manually from the browser console, but apparently the selection list only gets added to the DOM when the button is clicked, and gets removed as soon as the mouse focus leaves the list. So it seems there's no easy workaround or this either.  The dropdown list really needs a scroll bar at very least!  But also pagination if it only retrieves 100 repos.

![image](https://github.com/calcom/synclinear.com/assets/100738/f2fd1b15-8414-4070-bff0-748c8f880bc0)

**Comment by tedspare** [comment]
Hey, thanks @aspiers - clicking on the dropdown, you should be able to search for the repo - does that work for you? Not sure if that's what's pictured.

Re pagination: there will be a "load more" button if you filter down and still don't see the repo.

In the meantime, I've bookmarked the scroll + DOM issues.

**Comment by aspiers** [comment]
Oh wow thanks, that actually worked! There are two UX problems, both of which would have prevented me from figuring out how to solve the problem without the hint in your previous message:

Firstly it's not at all obvious that the button transforms into a search field, and previously I had completely missed this because after clicking:
  - the `4. Search your repo...` doesn't disappear to make room for typing
  - no flashing cursor appears, which is the standard visual clue which users expect since pretty much every other active text field you can find will behave this way

Secondly, after typing a search field, as you predicted, a match didn't appear and I had to hit the "Load more" button twice.  Again this is not intuitive UX, because it doesn't look like normal pagination, so the user will not realise that behind the scenes only 100 entries are loaded and they need to keep clicking until their match appears.  This is aggravated by the fact that there is no visible change after clicking "Load more".

**Comment by tedspare** [comment]
Lots to learn here, thanks a ton @aspiers. Added to my notes - expect the search and pagination UX to be fixed soon.

**Comment by aspiers** [comment]
Thanks so much @tedspare!

**Comment by vany365** [comment]
Hey thanks for looking into this. There appears to be an issue while im the owner of an org. here are the options i am able to see but I am an owner of this org and zero repos from it are showing as an option for me. https://github.com/ApeWorX
<img width="1477" alt="Screenshot 2023-07-12 at 12 50 27 PM" src="https://github.com/calcom/synclinear.com/assets/37391032/2f659caa-faa6-4dbe-b2b1-11ec2fe3feb4">

**Comment by vany365** [comment]
Seems i need to login as the organization account? but in the steps i am not seeing how to do that. if you have any recommendations or suggestions that would be great! thanks

**Comment by tedspare** [comment]
Hi @vany365 - to sign in as the org account (if the site logs you into `vany365` by default), sign out (`X` at the top right) then go to [GitHub settings > Applications](https://github.com/settings/installations) > maige-bot > Configure and click Uninstall at the bottom. After that, please try to log back in and let me know if the org account doesn't show 🙌

![image](https://github.com/calcom/synclinear.com/assets/36117635/d61fdba1-779c-4663-8eea-fd7898bc4708)

**Comment by tedspare** [comment]
@aspiers the repo selection UX should be fixed in 0e88983ad24f33de5fe4898a864583042f0d8a3c

Considering the missing repos as an account issue, Vany - feel free to re-open if I'm wrong  🙌
