### ISSUE TITLE
why write permissions?

### ISSUE THREAD

**Issue by PeerRich** [calcom/synclinear.com#47]
from a potential user:

> why does it need the permission to write code to public/private repositories?

**Comment by PeerRich** [comment]
@tedspare do you know more?

**Comment by tedspare** [comment]
The `repo` scope (the most generous) could possibly be replaced by the stricter `repo:status` scope, which grants access to commits but not code. Open to PRs testing this!

**Comment by PeerRich** [comment]
can someone fork and test with less scope?

**Comment by tedspare** [comment]
Finally tested this:
- Edited the GitHub scopes [here](https://github.com/calcom/synclinear.com/blob/main/utils/constants.ts#L41)
- Revoked my access token [here](https://github.com/organizations/neat-run/settings/applications)
- Re-authorized GitHub via the UI. Ensured the stricter scopes showed.
❌ A subset of repos were shown in the dropdown (excluding this one for me)
- Successfully synced a personal repo
❌ Comments, edits, labels, etc failed to sync to GitHub with 403s (forbidden)

 The `repo` scopes lives another day - could potentially limit to `public_repo` since this project is only for those

Otherwise, closing this
