### ISSUE TITLE
Unable to connect: "Failed to save sync"

### ISSUE THREAD

**Issue by vanessayuenn** [calcom/synclinear.com#49]
Hi, I am trying to set up synclinear and I am not able to get pass the webhook deployment step. I keep getting "Failed to save sync" error, even though I can see that the webhooks have been deployed correctly to both apps. 

I tried deleting it and reinstalling, but no dice. I suspect that when I first set it up, I let the initial authorisation timed out by accident, resulting in some orphaned data in the DB that didn't get cleared out when I uninstalled the apps from Linear/GitHub's end. How can I go about doing a full reset? Thanks!

**Comment by tedspare** [comment]
Thanks for raising this @vanessayuenn! Your explanation seems very plausible. Orphaned data would break some of the setup steps.

If you'd like that data to be wiped for a fresh start, which repos and Linear teams should I remove? If that doesn't work, I'll try to replicate this.

**Comment by vanessayuenn** [comment]
@tedspare this would be for: `storybookjs/storybook` on GitHub and `Storybook` on Linear. Thank you!

**Comment by tedspare** [comment]
Removed, thanks! Please let me know if it fails to save again.

**Comment by vanessayuenn** [comment]
@tedspare thanks, but unfortunately I am still getting the same "Failed to save sync" error. 

However, I think when you removed things on your DB end, I still had the webhooks installed on both GitHub and Linear; not sure if that would have caused any issue. I have now removed the webhooks from both sides. Perhaps you can try again?

**Comment by tedspare** [comment]
All good - I've removed them again. Does that work?

**Comment by vanessayuenn** [comment]
@tedspare sorry this issue still persists. I should also share that the GitHub webhooks keep failing with the error "Could not find issue's corresponding team":
<img width="800" alt="image" src="https://user-images.githubusercontent.com/6842965/212098459-a147760d-e8c2-4521-ab64-64cf4a3133cc.png">

**Comment by tedspare** [comment]
Interesting - thanks @vanessayuenn. This error means the repo/team (or actual issue) wasn't found.

Did the "Failed to save sync" error persist, or were you able to set the app up?

**Comment by vanessayuenn** [comment]
@tedspare no i still get the "failed to save sync" error on synclinear.com side, and the "Could not find issue's corresponding team" error is on GitHub's webhook side (on all types of delivery). I also cross-check the request bodies on calls to `synclinear.com/api/save` vs GitHub webhook deliveries, the `repoId` and `userId` match between the two calls.

**Comment by tedspare** [comment]
Thanks for the details - I haven't found the source of the error yet, but here are two more options:
- If you log into the dashboard at [SyncLinear.com](https://synclinear.com/), do you see any active syncs (see pic)? If so, could you try removing then re-syncing them?
- Otherwise, we could try resetting once more. If so, just let me know when you've deleted both webhooks manually and I'll reset your records in the DB.

![image](https://user-images.githubusercontent.com/36117635/212177302-f2ab5e1c-40d0-44db-a495-a49575b5d3b2.png)

**Comment by vanessayuenn** [comment]
Nope, I had not been able to get pass the deploy webhooks step to get to the screen you shared.

Ok let's try this again. Here is everything I have removed:
- Authorized application installed on Linear
- Authorized OAuth App installed on my profile on GitHub
- webhook on GitHub repo
- webhook on Linear

Is there something else I missed? Perhaps we can go one step further, not just resetting records for team on Linear and repo on GitHub, but my records as a user from the DB as well. Thanks again for all the help so far!

**Comment by tedspare** [comment]
Thank you for bearing with me @vanessayuenn! This is the trickiest bug so far in this project.

Here's what I've removed:
- `storybookjs/storybook` GitHub repo record

Finally noticed I haven't seen the `Storybook` Linear team in the DB, and its absence seems to be breaking the save. Is it possible that team has another name, a custom ID in Linear, or some special permission preventing its ID from being returned?
![image](https://user-images.githubusercontent.com/36117635/212393144-7af4befa-06d9-437d-b7d4-d93fcc3cd5b1.png)

Otherwise, feel free to try again and if it fails again, I can add the team manually. Storybook is probably a huge org too - happy to help set up self-hosting.

**Comment by vanessayuenn** [comment]
@tedspare I appreciate you working with me on this weird bug! It looks like the linear team ID did get returned, but for some reason cannot be written into the synclinear database; the error returned did not have details. Pasting the payload and response on `/api/linear/save` call:
```
payload object: {
    "teamId": "cf44ea4c-b6e2-4f26-97f0-09fc66a8d2f5",
    "teamName": "Storybook",
    "publicLabelId": "f30a265a-1d99-4387-9696-32a0ef9c40df",
    "canceledStateId": "e0807107-25d4-49e7-9378-fc1b0c775049",
    "doneStateId": "fafbf2f2-7370-4848-abbe-9f894cf98626"
}
error response: {
    "error":{"clientVersion":"3.15.2"}
}
```
Our team is actually pretty small, but if it's still a dead end from here, I will look into the self-hosting option also.

**Comment by tedspare** [comment]
Thanks for sharing the payload, @vanessayuenn. I've manually added the Linear team to the DB. The team's webhook should show as "deployed" now in the UI. Wanna try syncing one last time?

I'll look into what's causing that save to fail.

**Comment by Sandhukhizar61** [comment]
Camera file is not opening.

**Comment by tedspare** [comment]
Hi @Sandhukhizar61 - not sure I understand what you mean but feel free to open a [new issue](https://github.com/calcom/synclinear.com/issues/new)!
