### ISSUE TITLE
Can't use synclinear with some organization repositories

### ISSUE THREAD

**Issue by rmFlynn** [calcom/synclinear.com#60]
I have some organization repositories for which this tool will not work and some for which it will, and I can't for the life of me figure out why. I have tested it, and it is all the things I dreamed of and more, but I can't use it on the repository I want to most of all. The repository is part of a GitHub organization, of which I am the owner and a member. I can use sync linear on repositories of another organization, of which I am only a member of a team. I can't figure out what is different between the two. 

To be clear, the repositories I can't add simply don't show up in the dropdown. I know I can add web hooks to these repositories through 3rd party apps because I do so for CircleCI.

I will continue to explore your code base, but any time you can give to this confusion is much appreciated!

**Comment by tedspare** [comment]
Hey @rmFlynn, thanks for raising this.

The repo dropdown only fetches the first 100 repos (the maximum per fetch) - is it possible there are >100 repos available to you? If so, a permanent fix would be a "show more" or infinite scroll in the dropdown (open to PRs for this! Would start [here](https://github.com/calcom/synclinear.com/blob/main/components/GitHubAuthButton.tsx#L182)).

If you see <100 repos in the dropdown, I know some orgs require explicit access for 3rd-party apps, accessible at `github.com/orgs/<org-name>/policies/applications` > SyncLinear > "grant access".

Let me know if neither of these help!

**Comment by rmFlynn** [comment]
Thanks for your fast response! I am still impressed with your tool. In my case, the repository number was not the problem. It may be the permissions problem, but my team changed plans at the last minute, so I was not able to test the theory. Still, your advice was super helpful! I am going to close this ticket seeing as I don't think that synclinear was the problem and i don't have anything to contribute. Keep up the good work! I will see if I can tip your org.

**Comment by aspiers** [comment]
> The repo dropdown only fetches the first 100 repos (the maximum per fetch) - is it possible there are >100 repos available to you? If so, a permanent fix would be a "show more" or infinite scroll in the dropdown (open to PRs for this! Would start [here](https://github.com/calcom/synclinear.com/blob/main/components/GitHubAuthButton.tsx?rgh-link-date=2023-02-06T14%3A43%3A12Z#L182)).

I see 99 repos (or perhaps 100, I might have miscounted), and the one I want to sync is not there.  So this is definitely a problem for me - please could you reopen the issue?  A "show more" or infinite scroll would not be great UX; when you have > 100 repos, this would lead to a lot of tedious scrolling and visual searching.  The problem is compounded by the fact that the list is unsorted.

Instead, I would suggest a text field above the dropdown which you can type in to do a substring search which narrows down the results to only repos matching that substring.

> If you see <100 repos in the dropdown, I know some orgs require explicit access for 3rd-party apps, accessible at `github.com/orgs/<org-name>/policies/applications` > SyncLinear > "grant access".

BTW this link did not work for me, but the following did: `https://github.com/organizations/<org-name>/settings/oauth_application_policy`
